# Generated by Django 4.2 on 2024-05-01 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like',
            field=models.ManyToManyField(related_name='liked', to='products.product'),
        ),
    ]
