# Generated by Django 4.2 on 2024-04-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_gender_user_nickname_user_self_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, default='1998-02-03'),
            preserve_default=False,
        ),
    ]
